env:
  global:
    - CC_TEST_REPORTER_ID=119e83a979e3bc17986e14fdcd75f1fb22cc71e794553b5c469d35f6b8f4076b
language: python
python:
  # - "3.4"
  # - "3.5"
  - "3.6"
  # PyPy versions
  # - "pypy2.7"
  # - "pypy3.5"
install:
  - pip install Django
  - pip install PyYAML
  - pip install python-coveralls
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - coverage run --source=bootstrap_datepicker_plus runtests.py
  - coverage xml
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - coveralls
